[package]
name = "masto-rpg"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = "1.39.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.mastodon-async]
version = "1.0"
features = ["toml", "mt"]
